// Generated by CoffeeScript 1.4.0
(function() {
  var canvas, context, putPoint, radius;

  canvas = document.getElementById('draw');

  context = canvas.getContext('2d');

  radius = 10;

  canvas.width = window.innerWidth;

  canvas.height = window.innerHeight;

  putPoint = function(e) {
    context.beginPath();
    context.arc(e.offsetX, e.offsetY, radius, 0, Math.PI * 2);
    return context.fill();
  };

  canvas.addEventListener('mousedown', putPoint);

}).call(this);
